erDiagram
    "user (PostgreSQL)" {
        int id PK
        varchar name
        varchar email
    }

    "users (MongoDB collection)" {
        ObjectId _id PK
        string name
        string email
    }
